### ISSUE TITLE
[BUG]: .config/ftl/etc/bin/ftl: line 102: pviewers: command not found

### ISSUE THREAD

**Issue by zenny** [nkh/ftl#2]
Hi @nkh 

Thanks for sharing a down-to-earth bash file viewer with preview enabled that merits over lf, directed from https://github.com/ranger/ranger/issues/1580#issuecomment-498047266 

1. Tried to install without messing with `brew` and other stuffs in voidlinux, the installation went alright but it breaks with:

`.config/ftl/etc/bin/ftl: line 102: pviewers: command not found`

2. Thereafter a text console opens up on `ret`, that opens up in `nvim` that has a content that reads:

```
pgrep cmus &>/dev/null || { tmux new-session -s cmus -d "$(which cmus)" &>/dev/null ; until pgrep cmus &>/dev/null ; do sleep 0.01 ; done ; sleep 1 ; }
cmus-remote -q "$@" ; cmus-remote -Q | grep -qs 'status playing' || cmus-remote -p 

# vim: set filetype=sh :
```

I have got `cmus-2.10.0` and `tmux-3.3a` installed.

3. And further reports `$FTL_CFG/viewers/core` falsely reports `does not exist`!

`/home/zenny/.config/ftl/etc/ftlrc: line 129: /home/zenny/.config/ftl/viewers/core: No such file or directory`

whereas `/home/zenny/.config/ftl/viewers/core` does exist and reads exactly as `https://github.com/nkh/ftl/raw/main/config/ftl/etc/viewers/core`

Any clues. Cheers,

Mvh,
/z

**Comment by nkh** [comment]
Well, this is a surprise! At least one other person in the universe uses tmux and vim!
I  think you're in for a treat (if you can live with a few quirks). Since you're user number Uno, you're going to be VIP, IE: suffer with me ;).

hmm, pviewer is the entry point for previews,  same as riffle in ranger, and it's part of ftl. if that doesn't work then probably nothing will.

# questions

I guess you have installed the latest from the repo, right? Can you "find" '.../ftl/etc/viewers/core' on your disk?

What does you $FTL_CFG contain?

I guess that $EDITOR=nvim on your machine

# brew stuff you haven't installed are

## optional pager
brew install moar

that's OK it's not the default pager but get brew working IMHO

## json viewers
brew install fx
brew install jless

In the config we have

JSON_VIEWER=jless

if you don't want to install jless, which I recommend  you do, you'll need to override that variable in your own ftlrc

## ultimate plumber pipeline TUI
brew install up 

up is a pretty cool application if you write a lot of pipelines, it's used with the binding defined at config/ftl/bindings/via_bash:35:1

bind ftl file yX      up_select               "select file via the ultimate plumber"

it's an advance way to select files by running a pipeline via up. the simplest is to redefine that binding in your ftlrc, or ... not and if you happen to press yX, you'll get an error message. ftl is not shielding you from the system, it puts you right in the middle of it for good and bad.

PS: I haven't used cmus for a while, I play music from an instance of ftl most of the time. Support level may vary on that one.

**Comment by nkh** [comment]
Hmm, re-reading you text above I wonder if you understood that ftl is a file manager, I used ranger a few years ago then I replaced it with ftl which works like I want it to (integrated and following the Unix philosophy).

**Comment by zenny** [comment]
> Hmm, re-reading you text above I wonder if you understood that ftl is a file manager, I used ranger a few years ago then I replaced it with ftl which works like I want it to (integrated and following the Unix philosophy).

Thanks for your inputs and adhering to *nix philosophy. Yet I find myself too much distracted to go with multiple package managers. I prefer to go with the source instead of going through several layers of processes. Say I am fond of suckless.org tools among which I use heavily `st` and `sent` (modified). The only thing I missed is the ability to scroll previews in `lf`, and therefore I checked with your admirable work. Actually I am fond of 'dired-mode` in emacs.

Cheers and have a nice week,

Mvh,
/z
